/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package main.java.com.mycompany.sigeliapp.vistas;

/**
 *
 * @author Eduar Xavier
 */
public class adminLibros extends javax.swing.JFrame {

    /** Creates new form panelAdministrador */
    public adminLibros() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        txtNombrePersona = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnOpcionesPanelAdmin = new javax.swing.JButton();
        txtCargo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnVolverPanel = new javax.swing.JButton();
        panel1 = new javax.swing.JPanel();
        txtNombreLibro1 = new javax.swing.JLabel();
        txtNombreAutor1 = new javax.swing.JLabel();
        txtEstanteLibro1 = new javax.swing.JLabel();
        txtFilaLibro1 = new javax.swing.JLabel();
        txtDisponibilidadLibro1 = new javax.swing.JLabel();
        txtAnoLibro1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        backPagAdmin = new javax.swing.JButton();
        nextPagAdmin = new javax.swing.JButton();
        txtIngresoBusqueda = new javax.swing.JTextField();
        txtBusquedaAdmin = new javax.swing.JLabel();
        txtCantLibroAdmin = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        txtNombreLibro2 = new javax.swing.JLabel();
        txtNombreAutor2 = new javax.swing.JLabel();
        txtEstanteLibro2 = new javax.swing.JLabel();
        txtFilaLibro2 = new javax.swing.JLabel();
        txtDisponibilidadLibro2 = new javax.swing.JLabel();
        txtAnoLibro2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        panel3 = new javax.swing.JPanel();
        txtNombreLibro3 = new javax.swing.JLabel();
        txtNombreAutor3 = new javax.swing.JLabel();
        txtEstanteLibro3 = new javax.swing.JLabel();
        txtFilaLibro3 = new javax.swing.JLabel();
        txtDisponibilidadLibro3 = new javax.swing.JLabel();
        txtAnoLibro3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        panel4 = new javax.swing.JPanel();
        txtNombreLibro4 = new javax.swing.JLabel();
        txtNombreAutor4 = new javax.swing.JLabel();
        txtEstanteLibro4 = new javax.swing.JLabel();
        txtFilaLibro4 = new javax.swing.JLabel();
        txtDisponibilidadLibro4 = new javax.swing.JLabel();
        txtAnoLibro4 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        panel5 = new javax.swing.JPanel();
        txtNombreLibro5 = new javax.swing.JLabel();
        txtNombreAutor5 = new javax.swing.JLabel();
        txtEstanteLibro5 = new javax.swing.JLabel();
        txtFilaLibro5 = new javax.swing.JLabel();
        txtDisponibilidadLibro5 = new javax.swing.JLabel();
        txtAnoLibro5 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        btnCopiarISBN5 = new javax.swing.JButton();
        btnBusqueda = new javax.swing.JButton();
        btnCopiarISBN2 = new javax.swing.JButton();
        btnCopiarISBN3 = new javax.swing.JButton();
        btnCopiarISBN4 = new javax.swing.JButton();
        btnCopiarISBN1 = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        txtNombrePersona.setBackground(new java.awt.Color(204, 204, 204));
        txtNombrePersona.setForeground(new java.awt.Color(204, 204, 204));
        txtNombrePersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombrePersona.setText("jLabel1");

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnOpcionesPanelAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnOpcionesPanelAdmin.setText("jButton7");
        btnOpcionesPanelAdmin.setBorder(null);
        btnOpcionesPanelAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpcionesPanelAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionesPanelAdminActionPerformed(evt);
            }
        });

        txtCargo.setBackground(new java.awt.Color(204, 204, 204));
        txtCargo.setForeground(new java.awt.Color(204, 204, 204));
        txtCargo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCargo.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombrePersona, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(txtCargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(btnOpcionesPanelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOpcionesPanelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCargo))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jPanel2.setBackground(new java.awt.Color(246, 114, 114));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolverPanel.setBackground(new java.awt.Color(255, 255, 255));
        btnVolverPanel.setText("btnVolver");
        btnVolverPanel.setBorder(null);
        btnVolverPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolverPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverPanelActionPerformed(evt);
            }
        });
        jPanel2.add(btnVolverPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 39, 36));

        panel1.setBackground(new java.awt.Color(255, 51, 51));

        txtNombreLibro1.setText("jLabel3");

        txtNombreAutor1.setText("jLabel4");

        txtEstanteLibro1.setText("jLabel5");

        txtFilaLibro1.setText("jLabel6");

        txtDisponibilidadLibro1.setText("jLabel7");

        txtAnoLibro1.setText("jLabel8");

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreLibro1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(txtNombreAutor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDisponibilidadLibro1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(txtAnoLibro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEstanteLibro1)
                    .addComponent(txtFilaLibro1))
                .addGap(20, 20, 20))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(txtNombreLibro1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreAutor1))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDisponibilidadLibro1)
                            .addComponent(txtEstanteLibro1))
                        .addGap(14, 14, 14)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFilaLibro1)
                            .addComponent(txtAnoLibro1)))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel2.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 590, 60));

        backPagAdmin.setText("jButton1");
        backPagAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backPagAdminActionPerformed(evt);
            }
        });
        jPanel2.add(backPagAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 50, 40));

        nextPagAdmin.setText("jButton1");
        nextPagAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPagAdminActionPerformed(evt);
            }
        });
        jPanel2.add(nextPagAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, 50, 40));

        txtIngresoBusqueda.setBackground(new java.awt.Color(153, 153, 153));
        txtIngresoBusqueda.setForeground(new java.awt.Color(51, 51, 51));
        txtIngresoBusqueda.setBorder(null);
        jPanel2.add(txtIngresoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 560, 30));

        txtBusquedaAdmin.setForeground(new java.awt.Color(51, 51, 51));
        txtBusquedaAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBusquedaAdmin.setText("jLabel1");
        jPanel2.add(txtBusquedaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 60, 580, -1));

        txtCantLibroAdmin.setForeground(new java.awt.Color(51, 51, 51));
        txtCantLibroAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCantLibroAdmin.setText("jLabel2");
        jPanel2.add(txtCantLibroAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 280, -1));

        panel2.setBackground(new java.awt.Color(255, 51, 51));

        txtNombreLibro2.setText("jLabel3");

        txtNombreAutor2.setText("jLabel4");

        txtEstanteLibro2.setText("jLabel5");

        txtFilaLibro2.setText("jLabel6");

        txtDisponibilidadLibro2.setText("jLabel7");

        txtAnoLibro2.setText("jLabel8");

        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreLibro2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(txtNombreAutor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDisponibilidadLibro2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(txtAnoLibro2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEstanteLibro2)
                    .addComponent(txtFilaLibro2))
                .addGap(20, 20, 20))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(txtNombreLibro2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreAutor2))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDisponibilidadLibro2)
                            .addComponent(txtEstanteLibro2))
                        .addGap(14, 14, 14)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFilaLibro2)
                            .addComponent(txtAnoLibro2)))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel2.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        panel3.setBackground(new java.awt.Color(255, 51, 51));

        txtNombreLibro3.setText("jLabel3");

        txtNombreAutor3.setText("jLabel4");

        txtEstanteLibro3.setText("jLabel5");

        txtFilaLibro3.setText("jLabel6");

        txtDisponibilidadLibro3.setText("jLabel7");

        txtAnoLibro3.setText("jLabel8");

        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreLibro3, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(txtNombreAutor3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDisponibilidadLibro3, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(txtAnoLibro3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEstanteLibro3)
                    .addComponent(txtFilaLibro3))
                .addGap(20, 20, 20))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(txtNombreLibro3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreAutor3))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDisponibilidadLibro3)
                            .addComponent(txtEstanteLibro3))
                        .addGap(14, 14, 14)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFilaLibro3)
                            .addComponent(txtAnoLibro3)))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel2.add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        panel4.setBackground(new java.awt.Color(255, 51, 51));

        txtNombreLibro4.setText("jLabel3");

        txtNombreAutor4.setText("jLabel4");

        txtEstanteLibro4.setText("jLabel5");

        txtFilaLibro4.setText("jLabel6");

        txtDisponibilidadLibro4.setText("jLabel7");

        txtAnoLibro4.setText("jLabel8");

        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreLibro4, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(txtNombreAutor4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDisponibilidadLibro4, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(txtAnoLibro4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEstanteLibro4)
                    .addComponent(txtFilaLibro4))
                .addGap(20, 20, 20))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(txtNombreLibro4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreAutor4))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDisponibilidadLibro4)
                            .addComponent(txtEstanteLibro4))
                        .addGap(14, 14, 14)
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFilaLibro4)
                            .addComponent(txtAnoLibro4)))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel2.add(panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        panel5.setBackground(new java.awt.Color(255, 51, 51));

        txtNombreLibro5.setText("jLabel3");

        txtNombreAutor5.setText("jLabel4");

        txtEstanteLibro5.setText("jLabel5");

        txtFilaLibro5.setText("jLabel6");

        txtDisponibilidadLibro5.setText("jLabel7");

        txtAnoLibro5.setText("jLabel8");

        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreLibro5, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(txtNombreAutor5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDisponibilidadLibro5, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(txtAnoLibro5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEstanteLibro5)
                    .addComponent(txtFilaLibro5))
                .addGap(20, 20, 20))
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addComponent(txtNombreLibro5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreAutor5))
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDisponibilidadLibro5)
                            .addComponent(txtEstanteLibro5))
                        .addGap(14, 14, 14)
                        .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFilaLibro5)
                            .addComponent(txtAnoLibro5)))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel2.add(panel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        btnCopiarISBN5.setText("jButton1");
        btnCopiarISBN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarISBN5ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCopiarISBN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 30, 40));

        btnBusqueda.setText("jButton1");
        btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaActionPerformed(evt);
            }
        });
        jPanel2.add(btnBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 30, 30));

        btnCopiarISBN2.setText("jButton1");
        btnCopiarISBN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarISBN2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCopiarISBN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 30, 40));

        btnCopiarISBN3.setText("jButton1");
        btnCopiarISBN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarISBN3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCopiarISBN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 30, 40));

        btnCopiarISBN4.setText("jButton1");
        btnCopiarISBN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarISBN4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCopiarISBN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 30, 40));

        btnCopiarISBN1.setText("jButton1");
        btnCopiarISBN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarISBN1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCopiarISBN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 30, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBusquedaActionPerformed

    private void btnCopiarISBN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarISBN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCopiarISBN1ActionPerformed

    private void btnCopiarISBN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarISBN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCopiarISBN2ActionPerformed

    private void btnCopiarISBN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarISBN3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCopiarISBN3ActionPerformed

    private void btnCopiarISBN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarISBN4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCopiarISBN4ActionPerformed

    private void btnCopiarISBN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarISBN5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCopiarISBN5ActionPerformed

    private void backPagAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backPagAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backPagAdminActionPerformed

    private void nextPagAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPagAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextPagAdminActionPerformed

    private void btnVolverPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverPanelActionPerformed

    private void btnOpcionesPanelAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionesPanelAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpcionesPanelAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminLibros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton backPagAdmin;
    public javax.swing.JButton btnBusqueda;
    private javax.swing.JButton btnCopiarISBN1;
    private javax.swing.JButton btnCopiarISBN2;
    private javax.swing.JButton btnCopiarISBN3;
    private javax.swing.JButton btnCopiarISBN4;
    private javax.swing.JButton btnCopiarISBN5;
    public javax.swing.JButton btnOpcionesPanelAdmin;
    public javax.swing.JButton btnVolverPanel;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    public javax.swing.JButton nextPagAdmin;
    public javax.swing.JPanel panel1;
    public javax.swing.JPanel panel2;
    public javax.swing.JPanel panel3;
    public javax.swing.JPanel panel4;
    public javax.swing.JPanel panel5;
    public javax.swing.JLabel txtAnoLibro1;
    public javax.swing.JLabel txtAnoLibro2;
    public javax.swing.JLabel txtAnoLibro3;
    public javax.swing.JLabel txtAnoLibro4;
    public javax.swing.JLabel txtAnoLibro5;
    public javax.swing.JLabel txtBusquedaAdmin;
    public javax.swing.JLabel txtCantLibroAdmin;
    public javax.swing.JLabel txtCargo;
    public javax.swing.JLabel txtDisponibilidadLibro1;
    public javax.swing.JLabel txtDisponibilidadLibro2;
    public javax.swing.JLabel txtDisponibilidadLibro3;
    public javax.swing.JLabel txtDisponibilidadLibro4;
    public javax.swing.JLabel txtDisponibilidadLibro5;
    public javax.swing.JLabel txtEstanteLibro1;
    public javax.swing.JLabel txtEstanteLibro2;
    public javax.swing.JLabel txtEstanteLibro3;
    public javax.swing.JLabel txtEstanteLibro4;
    public javax.swing.JLabel txtEstanteLibro5;
    public javax.swing.JLabel txtFilaLibro1;
    public javax.swing.JLabel txtFilaLibro2;
    public javax.swing.JLabel txtFilaLibro3;
    public javax.swing.JLabel txtFilaLibro4;
    public javax.swing.JLabel txtFilaLibro5;
    public javax.swing.JTextField txtIngresoBusqueda;
    public javax.swing.JLabel txtNombreAutor1;
    public javax.swing.JLabel txtNombreAutor2;
    public javax.swing.JLabel txtNombreAutor3;
    public javax.swing.JLabel txtNombreAutor4;
    public javax.swing.JLabel txtNombreAutor5;
    public javax.swing.JLabel txtNombreLibro1;
    public javax.swing.JLabel txtNombreLibro2;
    public javax.swing.JLabel txtNombreLibro3;
    public javax.swing.JLabel txtNombreLibro4;
    public javax.swing.JLabel txtNombreLibro5;
    public javax.swing.JLabel txtNombrePersona;
    // End of variables declaration//GEN-END:variables

}
