/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.mycompany.sigeliapp.vistas;

/**
 *
 * @author Eduar Xavier
 */
public class panelAdminUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form panelAdminLibros
     */
    public panelAdminUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelExten = new javax.swing.JPanel();
        btnOpcionesPanelAdmin1 = new javax.swing.JLabel();
        txtNombrePersona1 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JLabel();
        btnExtenPanelOff = new javax.swing.JLabel();
        adminLibros = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panel4 = new javax.swing.JPanel();
        txtNombre4 = new javax.swing.JLabel();
        txtNombreAutor4 = new javax.swing.JLabel();
        txtDisponibilidadLibro4 = new javax.swing.JLabel();
        txtAnoLibro4 = new javax.swing.JLabel();
        panel5 = new javax.swing.JPanel();
        txtNombre5 = new javax.swing.JLabel();
        txtNombreAutor5 = new javax.swing.JLabel();
        txtDisponibilidadLibro5 = new javax.swing.JLabel();
        txtAnoLibro5 = new javax.swing.JLabel();
        backPagAdmin = new javax.swing.JButton();
        panel2 = new javax.swing.JPanel();
        txtNombre2 = new javax.swing.JLabel();
        txtNombreAutor2 = new javax.swing.JLabel();
        txtDisponibilidadLibro2 = new javax.swing.JLabel();
        txtAnoLibro2 = new javax.swing.JLabel();
        txtCantLibroAdmin = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        txtNombre1 = new javax.swing.JLabel();
        txtNombreAutor1 = new javax.swing.JLabel();
        txtDisponibilidadLibro1 = new javax.swing.JLabel();
        txtAnoLibro1 = new javax.swing.JLabel();
        txtBusquedaAdmin = new javax.swing.JLabel();
        nextPagAdmin = new javax.swing.JButton();
        panel3 = new javax.swing.JPanel();
        txtNombre3 = new javax.swing.JLabel();
        txtNombreAutor3 = new javax.swing.JLabel();
        txtDisponibilidadLibro3 = new javax.swing.JLabel();
        txtAnoLibro3 = new javax.swing.JLabel();
        btnPegar = new javax.swing.JButton();
        btnBusqueda = new javax.swing.JButton();
        txtIngresoBusqueda = new javax.swing.JTextField();
        btnVolverMenu = new javax.swing.JLabel();
        btnOpcionesPanelAdmin = new javax.swing.JLabel();
        txtNombrePersona = new javax.swing.JLabel();
        btnExtenPanel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelExten.setBackground(new java.awt.Color(126, 0, 0));

        btnOpcionesPanelAdmin1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\iconos\\iconoUsuario.png")); // NOI18N
        btnOpcionesPanelAdmin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtNombrePersona1.setBackground(new java.awt.Color(204, 204, 204));
        txtNombrePersona1.setForeground(java.awt.Color.white);
        txtNombrePersona1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombrePersona1.setText("jLabel1");

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\iconos\\inconoExit.png")); // NOI18N
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnExtenPanelOff.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExtenPanelOff.setForeground(java.awt.Color.white);
        btnExtenPanelOff.setText("x");
        btnExtenPanelOff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        adminLibros.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        adminLibros.setForeground(new java.awt.Color(204, 204, 204));
        adminLibros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminLibros.setText("Administrar libros");
        adminLibros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Añadir libros");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Administrar usuarios");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Ver prestamos");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Ver Multas");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Reportes");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelExtenLayout = new javax.swing.GroupLayout(panelExten);
        panelExten.setLayout(panelExtenLayout);
        panelExtenLayout.setHorizontalGroup(
            panelExtenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExtenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelExtenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExtenLayout.createSequentialGroup()
                        .addComponent(btnCerrarSesion)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExtenLayout.createSequentialGroup()
                        .addComponent(btnExtenPanelOff)
                        .addGap(16, 16, 16))))
            .addGroup(panelExtenLayout.createSequentialGroup()
                .addGroup(panelExtenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelExtenLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtNombrePersona1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelExtenLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnOpcionesPanelAdmin1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelExtenLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelExtenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelExtenLayout.setVerticalGroup(
            panelExtenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExtenLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(btnExtenPanelOff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOpcionesPanelAdmin1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombrePersona1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(adminLibros)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(268, 268, 268)
                .addComponent(btnCerrarSesion)
                .addGap(40, 40, 40))
        );

        getContentPane().add(panelExten, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 650));

        panel4.setBackground(new java.awt.Color(249, 249, 249));
        panel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        panel4.setForeground(new java.awt.Color(51, 51, 51));
        panel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtNombre4.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre4.setText("jLabel3");

        txtNombreAutor4.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreAutor4.setText("jLabel4");

        txtDisponibilidadLibro4.setForeground(new java.awt.Color(51, 51, 51));
        txtDisponibilidadLibro4.setText("jLabel7");

        txtAnoLibro4.setForeground(new java.awt.Color(51, 51, 51));
        txtAnoLibro4.setText("jLabel8");

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombre4, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(txtNombreAutor4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDisponibilidadLibro4, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(txtAnoLibro4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(txtNombre4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreAutor4))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(txtDisponibilidadLibro4)
                        .addGap(14, 14, 14)
                        .addComponent(txtAnoLibro4)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 660, -1));

        panel5.setBackground(new java.awt.Color(249, 249, 249));
        panel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        panel5.setForeground(new java.awt.Color(51, 51, 51));
        panel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtNombre5.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre5.setText("jLabel3");

        txtNombreAutor5.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreAutor5.setText("jLabel4");

        txtDisponibilidadLibro5.setForeground(new java.awt.Color(51, 51, 51));
        txtDisponibilidadLibro5.setText("jLabel7");

        txtAnoLibro5.setForeground(new java.awt.Color(51, 51, 51));
        txtAnoLibro5.setText("jLabel8");

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombre5, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(txtNombreAutor5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDisponibilidadLibro5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnoLibro5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre5)
                    .addComponent(txtDisponibilidadLibro5))
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreAutor5)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAnoLibro5)
                        .addContainerGap())))
        );

        getContentPane().add(panel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 660, -1));

        backPagAdmin.setBackground(new java.awt.Color(153, 153, 153));
        backPagAdmin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\iconos\\iconoBefore.png")); // NOI18N
        backPagAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backPagAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backPagAdminActionPerformed(evt);
            }
        });
        getContentPane().add(backPagAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 150, 40));

        panel2.setBackground(new java.awt.Color(249, 249, 249));
        panel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        panel2.setForeground(new java.awt.Color(51, 51, 51));
        panel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtNombre2.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre2.setText("jLabel3");

        txtNombreAutor2.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreAutor2.setText("jLabel4");

        txtDisponibilidadLibro2.setForeground(new java.awt.Color(51, 51, 51));
        txtDisponibilidadLibro2.setText("jLabel7");

        txtAnoLibro2.setForeground(new java.awt.Color(51, 51, 51));
        txtAnoLibro2.setText("jLabel8");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombre2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(txtNombreAutor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDisponibilidadLibro2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(txtAnoLibro2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(txtNombre2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreAutor2))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(txtDisponibilidadLibro2)
                        .addGap(14, 14, 14)
                        .addComponent(txtAnoLibro2)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 660, -1));

        txtCantLibroAdmin.setForeground(new java.awt.Color(51, 51, 51));
        txtCantLibroAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCantLibroAdmin.setText("jLabel2");
        getContentPane().add(txtCantLibroAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 580, 350, -1));

        panel1.setBackground(new java.awt.Color(249, 249, 249));
        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        panel1.setForeground(new java.awt.Color(51, 51, 51));
        panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtNombre1.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre1.setText("jLabel3");

        txtNombreAutor1.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreAutor1.setText("jLabel4");

        txtDisponibilidadLibro1.setForeground(new java.awt.Color(51, 51, 51));
        txtDisponibilidadLibro1.setText("jLabel7");

        txtAnoLibro1.setForeground(new java.awt.Color(51, 51, 51));
        txtAnoLibro1.setText("jLabel8");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombre1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(txtNombreAutor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDisponibilidadLibro1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(txtAnoLibro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre1)
                            .addComponent(txtDisponibilidadLibro1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreAutor1))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(txtAnoLibro1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 660, 70));

        txtBusquedaAdmin.setForeground(new java.awt.Color(51, 51, 51));
        txtBusquedaAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBusquedaAdmin.setText("jLabel1");
        getContentPane().add(txtBusquedaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 650, -1));

        nextPagAdmin.setBackground(new java.awt.Color(153, 153, 153));
        nextPagAdmin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\iconos\\iconoNext.png")); // NOI18N
        nextPagAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextPagAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPagAdminActionPerformed(evt);
            }
        });
        getContentPane().add(nextPagAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 560, 150, 40));

        panel3.setBackground(new java.awt.Color(249, 249, 249));
        panel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        panel3.setForeground(new java.awt.Color(51, 51, 51));
        panel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtNombre3.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre3.setText("jLabel3");

        txtNombreAutor3.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreAutor3.setText("jLabel4");

        txtDisponibilidadLibro3.setForeground(new java.awt.Color(51, 51, 51));
        txtDisponibilidadLibro3.setText("jLabel7");

        txtAnoLibro3.setForeground(new java.awt.Color(51, 51, 51));
        txtAnoLibro3.setText("jLabel8");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombre3, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(txtNombreAutor3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDisponibilidadLibro3, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addComponent(txtAnoLibro3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(txtNombre3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreAutor3))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(txtDisponibilidadLibro3)
                        .addGap(14, 14, 14)
                        .addComponent(txtAnoLibro3)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 660, -1));

        btnPegar.setBackground(new java.awt.Color(204, 204, 204));
        btnPegar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\iconos\\inconoPegar.png")); // NOI18N
        btnPegar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPegar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, 40, 30));

        btnBusqueda.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\iconos\\iconoLupaBusqueda.png")); // NOI18N
        btnBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(btnBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, 40, 30));

        txtIngresoBusqueda.setBackground(new java.awt.Color(153, 153, 153));
        txtIngresoBusqueda.setForeground(new java.awt.Color(51, 51, 51));
        txtIngresoBusqueda.setBorder(null);
        getContentPane().add(txtIngresoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 580, 30));

        btnVolverMenu.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnVolverMenu.setForeground(new java.awt.Color(51, 51, 51));
        btnVolverMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolverMenu.setText("<  Volver");
        btnVolverMenu.setToolTipText("");
        btnVolverMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 80, -1));

        btnOpcionesPanelAdmin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\iconos\\iconoUsuario.png")); // NOI18N
        getContentPane().add(btnOpcionesPanelAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 40, 50));

        txtNombrePersona.setBackground(new java.awt.Color(204, 204, 204));
        txtNombrePersona.setForeground(new java.awt.Color(204, 204, 204));
        txtNombrePersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombrePersona.setText("jLabel1");
        getContentPane().add(txtNombrePersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, -1));

        btnExtenPanel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnExtenPanel.setForeground(new java.awt.Color(255, 255, 255));
        btnExtenPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExtenPanel.setText(">");
        btnExtenPanel.setToolTipText(">");
        btnExtenPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnExtenPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 80, -1));

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Los usuarios son buscados por el numero de su documento y nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 580, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eduar Xavier\\Desktop\\EduarXavier\\sigeli\\Sigeli\\src\\main\\java\\main\\java\\com\\mycompany\\sigeliapp\\vistas\\imagenes\\interfazPaneles.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPegarActionPerformed

    private void backPagAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backPagAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backPagAdminActionPerformed

    private void nextPagAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPagAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextPagAdminActionPerformed

    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBusquedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelAdminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelAdminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelAdminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelAdminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelAdminUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel adminLibros;
    public javax.swing.JButton backPagAdmin;
    public javax.swing.JButton btnBusqueda;
    public javax.swing.JLabel btnCerrarSesion;
    public javax.swing.JLabel btnExtenPanel;
    public javax.swing.JLabel btnExtenPanelOff;
    public javax.swing.JLabel btnOpcionesPanelAdmin;
    public javax.swing.JLabel btnOpcionesPanelAdmin1;
    public javax.swing.JButton btnPegar;
    public javax.swing.JLabel btnVolverMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JButton nextPagAdmin;
    public javax.swing.JPanel panel1;
    public javax.swing.JPanel panel2;
    public javax.swing.JPanel panel3;
    public javax.swing.JPanel panel4;
    public javax.swing.JPanel panel5;
    public javax.swing.JPanel panelExten;
    public javax.swing.JLabel txtAnoLibro1;
    public javax.swing.JLabel txtAnoLibro2;
    public javax.swing.JLabel txtAnoLibro3;
    public javax.swing.JLabel txtAnoLibro4;
    public javax.swing.JLabel txtAnoLibro5;
    public javax.swing.JLabel txtBusquedaAdmin;
    public javax.swing.JLabel txtCantLibroAdmin;
    public javax.swing.JLabel txtDisponibilidadLibro1;
    public javax.swing.JLabel txtDisponibilidadLibro2;
    public javax.swing.JLabel txtDisponibilidadLibro3;
    public javax.swing.JLabel txtDisponibilidadLibro4;
    public javax.swing.JLabel txtDisponibilidadLibro5;
    public javax.swing.JTextField txtIngresoBusqueda;
    public javax.swing.JLabel txtNombre1;
    public javax.swing.JLabel txtNombre2;
    public javax.swing.JLabel txtNombre3;
    public javax.swing.JLabel txtNombre4;
    public javax.swing.JLabel txtNombre5;
    public javax.swing.JLabel txtNombreAutor1;
    public javax.swing.JLabel txtNombreAutor2;
    public javax.swing.JLabel txtNombreAutor3;
    public javax.swing.JLabel txtNombreAutor4;
    public javax.swing.JLabel txtNombreAutor5;
    public javax.swing.JLabel txtNombrePersona;
    public javax.swing.JLabel txtNombrePersona1;
    // End of variables declaration//GEN-END:variables
}
