/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package main.java.com.mycompany.sigeliapp.vistas;

/**
 *
 * @author Eduar Xavier
 */
public class panelAdministrador extends javax.swing.JFrame {

    /** Creates new form panelAdministrador */
    public panelAdministrador() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        txtNombrePersona = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnOpcionesPanelAdmin = new javax.swing.JButton();
        txtCargo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAddLibros = new javax.swing.JButton();
        btnAdminLibros = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnReportes = new javax.swing.JButton();
        btnAdmnUsuario = new javax.swing.JButton();
        btnPrestamos = new javax.swing.JButton();
        btnDeudas = new javax.swing.JButton();
        btnSalirPanelAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        txtNombrePersona.setBackground(new java.awt.Color(204, 204, 204));
        txtNombrePersona.setForeground(new java.awt.Color(204, 204, 204));
        txtNombrePersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombrePersona.setText("jLabel1");

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnOpcionesPanelAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnOpcionesPanelAdmin.setText("jButton7");
        btnOpcionesPanelAdmin.setBorder(null);
        btnOpcionesPanelAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtCargo.setBackground(new java.awt.Color(204, 204, 204));
        txtCargo.setForeground(new java.awt.Color(204, 204, 204));
        txtCargo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCargo.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombrePersona, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(txtCargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(btnOpcionesPanelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOpcionesPanelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCargo))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jPanel2.setBackground(new java.awt.Color(246, 114, 114));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddLibros.setBackground(new java.awt.Color(127, 116, 116));
        btnAddLibros.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnAddLibros.setForeground(new java.awt.Color(51, 51, 51));
        btnAddLibros.setText("Añadir libros");
        btnAddLibros.setBorder(null);
        btnAddLibros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnAddLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 150, 150));

        btnAdminLibros.setBackground(new java.awt.Color(127, 116, 116));
        btnAdminLibros.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnAdminLibros.setForeground(new java.awt.Color(51, 51, 51));
        btnAdminLibros.setText("Administrar libros");
        btnAdminLibros.setBorder(null);
        btnAdminLibros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdminLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLibrosActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdminLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 150, 150));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Usuarios");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        btnReportes.setBackground(new java.awt.Color(127, 116, 116));
        btnReportes.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(51, 51, 51));
        btnReportes.setText("Reportes");
        btnReportes.setBorder(null);
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 150, 150));

        btnAdmnUsuario.setBackground(new java.awt.Color(127, 116, 116));
        btnAdmnUsuario.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnAdmnUsuario.setForeground(new java.awt.Color(51, 51, 51));
        btnAdmnUsuario.setText("Administrar usuarios");
        btnAdmnUsuario.setBorder(null);
        btnAdmnUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnAdmnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 150, 150));

        btnPrestamos.setBackground(new java.awt.Color(127, 116, 116));
        btnPrestamos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnPrestamos.setForeground(new java.awt.Color(51, 51, 51));
        btnPrestamos.setText("Prestamos");
        btnPrestamos.setBorder(null);
        btnPrestamos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamosActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 150, 150));

        btnDeudas.setBackground(new java.awt.Color(127, 116, 116));
        btnDeudas.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnDeudas.setForeground(new java.awt.Color(51, 51, 51));
        btnDeudas.setText("Deudas");
        btnDeudas.setBorder(null);
        btnDeudas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnDeudas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 150, 150));

        btnSalirPanelAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnSalirPanelAdmin.setText("jButton7");
        btnSalirPanelAdmin.setBorder(null);
        btnSalirPanelAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnSalirPanelAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 39, 36));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(99, 260, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLibrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminLibrosActionPerformed

    private void btnPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrestamosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddLibros;
    public javax.swing.JButton btnAdminLibros;
    public javax.swing.JButton btnAdmnUsuario;
    public javax.swing.JButton btnDeudas;
    public javax.swing.JButton btnOpcionesPanelAdmin;
    public javax.swing.JButton btnPrestamos;
    public javax.swing.JButton btnReportes;
    public javax.swing.JButton btnSalirPanelAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel txtCargo;
    public javax.swing.JLabel txtNombrePersona;
    // End of variables declaration//GEN-END:variables

}
